version: "3.3"
services:
  tt-admitad:
    build:
      ./
    restart: always
    networks:
      - backend
    volumes:
      - ./src:/application/src
      - ./var:/application/var
    command: ["/application/dev.sh"]
    entrypoint: ["/application/wait-for-it.sh", "-s" , "-t", "60", "postgres-db:5432", "--"]

networks:
  backend:
