version: "3.3"
services:
  tt-admitad:
    build:
      ./
    env_file:
      - variables.env
    ports:
      - "9080:9080"
    networks:
      - backend
    command: ["/application/start.sh"]

  postgres-db:
    image: postgres:12.1-alpine
    restart: always
    networks:
        - backend
    volumes:
        - ./db-data:/var/lib/postgresql/data
        - ./tandb-auth/init-db.sql:/docker-entrypoint-initdb.d/init-tandb-auth.sql
        - ./tandb-vote/init-db.sql:/docker-entrypoint-initdb.d/init-tandb-vote.sql
    ports:
        - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    labels:
      NAME: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./redis:/data
    networks:
      - backend
    command: redis-server --appendonly yes

  nginx:
    restart: always
    image: nginx:1.15.2-alpine
    networks:
        - backend
    ports:
        - 80:80
    restart: "always"
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/static:/var/www/static

networks:
  backend:
